### ISSUE TITLE
Define license

### ISSUE THREAD

**Issue by chevdor** [dbr/vedirect-rs#2]
Hello @dbr, since I started investing quite some efforts on the project, I would love for the licensing to be better defined.

You may find https://choosealicense.com/ rather convenient. `MIT` is usually a no brainer IMO...

**Comment by dbr** [comment]
Licensed under unlicense public domain a while ago and forgot to close this

In the unlikely event someone needs it under a more "normal" license, feel free to open an new issue and I'd be happy to relicense it under MIT
